version: '3'
services:
  nginx:
    image: 'eddranca/fibonacci-nginx'
    mem_limit: 128m
    depends_on:
      - api
      - frontend
    restart: always
    ports:
      - '80:80'
    hostname: nginx
  api:
    image: 'eddranca/fibonacci-server'
    environment:
      - REDIS_URL=$REDIS_URL
      - PG_USER=$PG_USER
      - PG_HOST=$PG_HOST
      - PG_DATABASE=$PG_DATABASE
      - PG_PASSWORD=$PG_PASSWORD
      - PG_PORT=$PG_PORT
    mem_limit: 512m
    hostname: api
  frontend:
    image: 'eddranca/fibonacci-frontend'
    mem_limit: 128m
    hostname: frontend
  worker:
    image: 'eddranca/fibonacci-worker'
    mem_limit: 512m
    hostname: worker
    environment:
      - REDIS_URL=$REDIS_URL