name: Deploy Fibonacci Service
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build docker image
        run: docker build -t eddranca/fibonacci-frontend-test -f ./Frontend/Dockerfile.dev ./Frontend
      - name: Test
        run: docker run -e CI=true eddranca/fibonacci-frontend-test npm run test
  dockerfiles:
    needs: test-frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push frontend image
        uses: docker/build-push-action@v2
        with:
          context: ./Frontend
          platforms: linux/amd64
          push: true
          tags: eddranca/fibonacci-frontend
      - name: Build and push server image
        uses: docker/build-push-action@v2
        with:
          context: ./Server
          platforms: linux/amd64
          push: true
          tags: eddranca/fibonacci-server
      - name: Build and push worker image
        uses: docker/build-push-action@v2
        with:
          context: ./Worker
          platforms: linux/amd64
          push: true
          tags: eddranca/fibonacci-worker
      - name: Build and push nginx image
        uses: docker/build-push-action@v2
        with:
          context: ./nginx
          platforms: linux/amd64
          push: true
          tags: eddranca/fibonacci-nginx
  deploy:
    needs: dockerfiles
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
      - name: Deploy docker files to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: docker-fibonacci
          environment_name: Dockerfibonacci-env
          existing_bucket_name: elasticbeanstalk-eu-central-1-681919286903
          region: eu-central-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
